%YAML:1.0

cam0:
  T_imu_cam: #rotation from camera to IMU R_CtoI, position of camera in IMU p_CinI
    - [0, -1, 0, 0.1]
    - [ 1, 0, 0, 0.035]
    - [ 0, 0, 1, 0]
    - [ 0, 0, 0, 1]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [0, 0, 0, 0]
  distortion_model: radtan
  intrinsics: [238.35, 238.35, 200, 200] #fu, fv, cu, cv
  resolution: [400, 400]
  rostopic: /stereo/left/image_raw
cam1:
  T_imu_cam: #rotation from camera to IMU R_CtoI, position of camera in IMU p_CinI
    - [0, -1, 0, 0.1]
    - [ 1, 0, 0, -0.035]
    - [ 0, 0, 1, 0]
    - [ 0, 0, 0, 1]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [0, 0, 0, 0]
  distortion_model: radtan
  intrinsics: [238.35, 238.35, 200, 200] #fu, fv, cu, cv
  resolution: [400, 400]
  rostopic: /stereo/right/image_raw
